services:
  web:
    build: .
    ports:
     - "8080:8080"
     - "5678:5678"

    # pass in user:group from startup arg:
    # - $uid(id -u ${USER}) $gid(id -g ${USER}) docker compose up
    user: ${uid}:${gid}

    # specify .env file:
    # see https://docs.docker.com/compose/how-tos/environment-variables/set-environment-variables/
    # and https://stackoverflow.com/questions/49770999/docker-env-for-python-variables
    # and https://khabdrick-dev.medium.com/use-an-env-file-in-docker-286ec79d4543
    env_file:
      - .env  

    volumes:
     - type: bind
       source: ./database
       target: /code/database
     - type: bind
       source: .
       target: /code 